### ISSUE TITLE
remote render is black, somthing wrong

### ISSUE THREAD

**Issue by mrhaydari** [flutter-webrtc/flutter-webrtc-demo#164]
remote render is black

i use flutter-webrtc/flutter-webrtc-server to create websocket and TURN server on local , and i connected to local with port 8086

i checked this line comment ([118](https://github.com/flutter-webrtc/flutter-webrtc-demo/issues/118#issuecomment-801804745)) but not working !

when I call the active property in the remote stream I get this throw
```
E/flutter ( 5603): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: UnimplementedError
E/flutter ( 5603): #0      MediaStreamNative.active (package:flutter_webrtc/src/native/media_stream_impl.dart:102:22)
E/flutter ( 5603): #1      _CallSampleState._connect.<anonymous closure> (package:flutter_application_1/src/call_sample/call_sample.dart:108:89)
E/flutter ( 5603): #2      Signaling._createSession.<anonymous closure> (package:flutter_application_1/src/call_sample/signaling.dart:360:34)
E/flutter ( 5603): #3      RTCPeerConnectionNative.eventListener (package:flutter_webrtc/src/native/rtc_peerconnection_impl.dart:186:18)
E/flutter ( 5603): #4      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 5603): #5      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 5603): #6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 5603): #7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 5603): #8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 5603): #9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter ( 5603): #10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter ( 5603): #11     _rootRun (dart:async/zone.dart:1420:47)
E/flutter ( 5603): #12     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 5603): #13     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 5603): #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 5603): #15     _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 5603): #16     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 5603): #17     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 5603): #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 5603): #19     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 5603): #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 5603):
W/FlutterWebRTCPlugin( 5603): FlutterRTCVideoRenderer.setVideoTrack, set video track to e219cb12-651d-42d3-b0f5-39ef7920ef0e
```
Maybe this is not an important issue but when onMessage "offer" case call after newSession.pc?.setRemoteDescription method I get this 2 line

```
D/MediaConstraintsUtils( 5744): mandatory constraints are not a map
D/MediaConstraintsUtils( 5744): optional constraints are not an array

```
where is the problem from ?
i used nox emulator 

// flutter doctor

```
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1)
[√] VS Code (version 1.60.0)
[√] Connected device (4 available)
```

**Comment by mrhaydari** [comment]
fixed, I use my own [coturn ](https://github.com/coturn/coturn) TURN server and worked fine
